-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "currentTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "isPlaying" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "videoUrl" TEXT NOT NULL DEFAULT '';
